### ISSUE TITLE
Middleware are doubled

### ISSUE THREAD

**Issue by lastsamurai26** [Psycho0verload/traefik-crowdsec-stack#8]
What I have noticed is that the default@file is used twice. 

It is already entered in traefik.yml as the default path for websecure, so it no longer needs to be used as a label 

Extract from the traefik.yml
```
  websecure:
    address: ':443'
    http:
      middlewares:
        - default@file
        - traefik-bouncer@file

```

Extract from the traefik.yml of docker compose

```
   labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-dashboad.entrypoints: websecure
      traefik.http.routers.traefik-dashboad.middlewares: default@file, traefik-dashboard-auth@file
      traefik.http.routers.traefik-dashboad.rule: ${SERVICES_TRAEFIK_LABELS_TRAEFIK_HOST:-HOST(`traefik.yourdomain.com`)}
```

only the Traefik dashboard auth needs to be setted
```     traefik.http.routers.traefik-dashboad.middlewares: traefik-dashboard-auth@file```

like for Wordpress 
```      - "traefik.http.routers.wordpress.middlewares=default@file```
This line can be removed
